[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_social_media = "59chiAcJ99ttxaDLxcsJh8Be2tChirZfWsWxkd2SRGDj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nomadic/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
